CREATE TABLE STUDENTS_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    ACTION_TYPE VARCHAR2(20),
    STUDENT_ID NUMBER,
    STUDENT_NAME VARCHAR2(50),
    ACTION_TIMESTAMP TIMESTAMP
);

CREATE SEQUENCE STUDENTS_LOG_SEQ START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER STUDENTS_LOG_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
DECLARE
    v_action_type VARCHAR2(20);
BEGIN

    IF INSERTING THEN
        v_action_type := 'INSERT';
    ELSIF UPDATING THEN
        v_action_type := 'UPDATE';
    ELSIF DELETING THEN
        v_action_type := 'DELETE';
    END IF;

    INSERT INTO STUDENTS_LOG (LOG_ID, ACTION_TYPE, STUDENT_ID, STUDENT_NAME, ACTION_TIMESTAMP)
    VALUES (STUDENTS_LOG_SEQ.NEXTVAL, v_action_type, 
            CASE WHEN v_action_type = 'DELETE' THEN :OLD.ID ELSE :NEW.ID END,
            CASE WHEN v_action_type = 'DELETE' THEN :OLD.NAME ELSE :NEW.NAME END,
            SYSTIMESTAMP);
END;
/

INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (4, 'Emma Davis', 1);

DELETE FROM STUDENTS where name = 'Emma Davis';

SELECT * from students;
SELECT * FROM STUDENTS_LOG;


