CREATE OR REPLACE TRIGGER trigger_cascade_deletion
AFTER DELETE ON GROUPS
FOR EACH ROW
BEGIN
    IF :OLD.ID IS NOT NULL THEN
        DELETE FROM STUDENTS
        WHERE GROUP_ID = :OLD.ID;
    END IF;
END;
/
